name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install Dependencies
      - name: Install Dependencies
        run: |
          cd ui
          npm install

      # 4. Build Project
      - name: Build Project
        run: |
          cd ui
          npm run build

      # 5. Archive Build Artifacts
      - name: Archive Build Artifacts
        run: tar -czf dist.tar.gz ./ui/dist/

      # 6. Copy Build Artifacts to Server
      - name: Copy dist.tar.gz to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "dist.tar.gz"
          target: /home/u328440314/domains/tscreativestudio.com/public_html/vite-golang-app/ui/public/

      # 7. Extract Build Artifacts on Server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            tar -xzf /home/u328440314/domains/tscreativestudio.com/public_html/vite-golang-app/ui/public/dist.tar.gz -C /home/u328440314/domains/tscreativestudio.com/public_html/vite-golang-app/ui/public
            rm -rf /home/u328440314/domains/tscreativestudio.com/public_html/vite-golang-app/ui/public/dist.tar.gz
