name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install Dependencies
      - name: Install Dependencies
        run:  |
         cd ui 
         npm install

      # 4. Build Project
      - name: Build Project
        run: |
          cd ui
          npm run build

      - name: Archive Build Artifacts
        run: | 
          tar -czf dist.tar.gz ./ui/dist/
          ls -R ./ui/dist

      # 5. Copy Build Artifacts to Server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /home/u328440314/domains/tscreativestudio.com/public_html/vite-golang-app/ui/public/*
            mkdir -p /home/u328440314/domains/tscreativestudio.com/public_html/vite-golang-app/ui/public
            tar -xzf dist.tar.gz ./ui/dist/ -C /home/u328440314/domains/tscreativestudio.com/public_html/vite-golang-app/ui/public
