name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies (UI)
        run: |
          cd ui
          npm install

      - name: Build React App (UI)
        run: |
          cd ui
          npm run build

      - name: Deploy to Hostinger
        env:
            GH_TOKEN: ${{ secrets.PROD_ENV }}
        run: |
          cd ui
          echo "Token: $GH_TOKEN"
          git remote add toHostinger -t https://${GH_TOKEN}@github.com/janbu12/vite-golang-app.git
          git push toHostinger main --force
